version: "3.9"

services:
  host:
    build: .
    volumes:
      - ./nginx:/etc/nginx:ro
      - certbot/www:/var/www/certbot/:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot/www:/var/www/certbot/
volumes:
  certbot: