version: "3.9"

services:
  webserver:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_www:/var/www/certbot:ro
      - certbot_fullchain:/etc/nginx/ssl/spaceengineering.zone/fullchain.pem:ro
      - certbot_privkey:/etc/nginx/ssl/spaceengineering.zone/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot:rw
      - certbot_fullchain:/etc/letsencrypt/live/spaceengineering.zone/fullchain.pem:rw
      - certbot_privkey:/etc/letscencrypt/live/spaceengineering.zone/privkey.pem
volumes:
  certbot_www:
  certbot_fullchain:
  certbot_privkey: