version: "3.9"

services:
  webserver:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_www:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot:rw
volumes:
  certbot_www: